"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: 09ac3aca3ef9
Revises: 5cbe584e8dcb
Create Date: 2025-10-17 20:56:51.882994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ac3aca3ef9'
down_revision = '5cbe584e8dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_no', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.drop_column('installment_no')

    # ### end Alembic commands ###
