"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: 1a6681084e1e
Revises: 3d35a367722a
Create Date: 2025-10-17 21:40:45.867988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6681084e1e'
down_revision = '3d35a367722a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_interest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_account', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_interest', schema=None) as batch_op:
        batch_op.drop_column('interest_account')

    # ### end Alembic commands ###
