"""Add loan_type field to loans

Revision ID: 1b080cb7e93b
Revises: f7d968c0b88c
Create Date: 2025-10-24 22:34:23.024297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b080cb7e93b'
down_revision = 'f7d968c0b88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('loan_type')

    # ### end Alembic commands ###
