"""transaction

Revision ID: 24755ae9ce8e
Revises: 5e34867790e8
Create Date: 2025-10-18 17:52:39.339327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24755ae9ce8e'
down_revision = '5e34867790e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.add_column(sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('credit_amount')
        batch_op.drop_column('debit_amount')

    # ### end Alembic commands ###
