"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: 333d9100f6c4
Revises: 3aaec17ed1ac
Create Date: 2025-10-17 20:46:38.572367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333d9100f6c4'
down_revision = '3aaec17ed1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_guarantors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_no', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('loan_guarantors_loan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'loans', ['loan_no'], ['loan_no'])
        batch_op.drop_column('loan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_guarantors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loan_guarantors_loan_id_fkey'), 'loans', ['loan_id'], ['id'])
        batch_op.drop_column('loan_no')

    # ### end Alembic commands ###
