"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: 3aaec17ed1ac
Revises: e47c7a976aab
Create Date: 2025-10-17 20:14:34.689683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aaec17ed1ac'
down_revision = 'e47c7a976aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disbursed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['disbursed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('disbursed_by')

    # ### end Alembic commands ###
