"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: 3d35a367722a
Revises: 1298cdd83bac
Create Date: 2025-10-17 21:36:42.118612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d35a367722a'
down_revision = '1298cdd83bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_interest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_no', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('loan_interest_loan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'loans', ['loan_no'], ['loan_no'])
        batch_op.drop_column('loan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_interest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loan_interest_loan_id_fkey'), 'loans', ['loan_id'], ['id'])
        batch_op.drop_column('loan_no')

    # ### end Alembic commands ###
