"""add GLTransaction model

Revision ID: 4104bc6716fe
Revises: 62918c76c8f3
Create Date: 2025-10-14 21:58:32.585952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4104bc6716fe'
down_revision = '62918c76c8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_no', sa.String(length=30), nullable=False),
    sa.Column('gl_code', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tran_type', sa.String(length=10), nullable=False),
    sa.Column('narration', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('posted_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['gl_code'], ['gl_accounts.gl_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gl_transactions')
    # ### end Alembic commands ###
