"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: 5cbe584e8dcb
Revises: 3feb683c3f37
Create Date: 2025-10-17 20:51:20.769485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbe584e8dcb'
down_revision = '3feb683c3f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_no', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('loan_schedules_loan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'loans', ['loan_no'], ['loan_no'])
        batch_op.drop_column('loan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loan_schedules_loan_id_fkey'), 'loans', ['loan_id'], ['id'])
        batch_op.drop_column('loan_no')

    # ### end Alembic commands ###
