"""members

Revision ID: 5e34867790e8
Revises: 9430103bb3c2
Create Date: 2025-10-18 14:42:31.869782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e34867790e8'
down_revision = '9430103bb3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_accounts', schema=None) as batch_op:
        batch_op.drop_column('interest_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
