"""Add loan_type field to loans

Revision ID: 81c63249b710
Revises: 1b080cb7e93b
Create Date: 2025-10-24 22:37:51.842474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c63249b710'
down_revision = '1b080cb7e93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_balance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('loan_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('loan_type')
        batch_op.drop_column('interest_balance')

    # ### end Alembic commands ###
