"""change tran_type to string

Revision ID: 8222b9d514be
Revises: 4104bc6716fe
Create Date: 2025-10-17 10:33:18.384950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8222b9d514be'
down_revision = '4104bc6716fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_guarantors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('guarantor_no', sa.String(length=20), nullable=True),
    sa.Column('amount_guaranteed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('interest_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('loan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('principal_due',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('interest_due',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('principal_paid',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('interest_paid',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=True)
        batch_op.drop_column('is_paid')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_no', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('member_no', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('loan_account', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('interest_account', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('disbursed_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.create_unique_constraint(None, ['loan_no'])
        batch_op.drop_constraint(batch_op.f('loans_member_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'members', ['member_no'], ['member_no'])
        batch_op.drop_column('outstanding_principal')
        batch_op.drop_column('disbursement_date')
        batch_op.drop_column('annual_rate')
        batch_op.drop_column('principal')
        batch_op.drop_column('member_id')
        batch_op.drop_column('term_months')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_months', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('principal', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('annual_rate', sa.NUMERIC(precision=7, scale=6), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('disbursement_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('outstanding_principal', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loans_member_id_fkey'), 'members', ['member_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('disbursed_date')
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('period')
        batch_op.drop_column('amount')
        batch_op.drop_column('interest_account')
        batch_op.drop_column('loan_account')
        batch_op.drop_column('member_no')
        batch_op.drop_column('loan_no')

    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('interest_paid',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
        batch_op.alter_column('principal_paid',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
        batch_op.alter_column('interest_due',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
        batch_op.alter_column('principal_due',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('loan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')

    op.drop_table('loan_interest')
    op.drop_table('loan_guarantors')
    # ### end Alembic commands ###
