"""add saccoAccounts details columns

Revision ID: 8e8324f9fc6a
Revises: e6525f2b20bb
Create Date: 2025-10-11 17:10:53.436446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8324f9fc6a'
down_revision = 'e6525f2b20bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gl_code', sa.String(length=20), nullable=False),
    sa.Column('gl_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gl_code')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('txn_no', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('member_no', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_no', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gl_account', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('running_balance', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('narration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_txn_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('tran_type', sa.Enum('debit', 'credit', name='tran_type_enum'), nullable=False))
        batch_op.add_column(sa.Column('posted_by', sa.String(length=50), nullable=False))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['txn_no'])
        batch_op.drop_constraint(batch_op.f('transactions_member_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('transactions_loan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sacco_accounts', ['account_no'], ['account_number'])
        batch_op.create_foreign_key(None, 'members', ['member_no'], ['member_no'])
        batch_op.drop_column('description')
        batch_op.drop_column('member_id')
        batch_op.drop_column('loan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transactions_loan_id_fkey'), 'loans', ['loan_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('transactions_member_id_fkey'), 'members', ['member_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
        batch_op.drop_column('posted_by')
        batch_op.drop_column('tran_type')
        batch_op.drop_column('bank_txn_date')
        batch_op.drop_column('narration')
        batch_op.drop_column('reference')
        batch_op.drop_column('running_balance')
        batch_op.drop_column('gl_account')
        batch_op.drop_column('account_no')
        batch_op.drop_column('member_no')
        batch_op.drop_column('txn_no')

    op.drop_table('gl_accounts')
    # ### end Alembic commands ###
