"""members

Revision ID: 9430103bb3c2
Revises: ecbd72186cd3
Create Date: 2025-10-18 14:37:20.035664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9430103bb3c2'
down_revision = 'ecbd72186cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_interest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_account', sa.String(length=20), nullable=False))

    with op.batch_alter_table('sacco_accounts', schema=None) as batch_op:
        batch_op.drop_column('interest_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))

    with op.batch_alter_table('loan_interest', schema=None) as batch_op:
        batch_op.drop_column('interest_account')

    # ### end Alembic commands ###
