"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: a4d5e33beaf9
Revises: 09ac3aca3ef9
Create Date: 2025-10-17 21:05:47.402821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d5e33beaf9'
down_revision = '09ac3aca3ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_balance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.alter_column('installment_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.alter_column('installment_no',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('principal_balance')

    # ### end Alembic commands ###
