"""members

Revision ID: b2e72f0a36db
Revises: 1a6681084e1e
Create Date: 2025-10-18 13:04:13.113394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e72f0a36db'
down_revision = '1a6681084e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'members', ['account_name'], ['name'])
        batch_op.drop_column('interest_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_name')

    # ### end Alembic commands ###
