"""Add loan_type field to loans

Revision ID: b9ae7c328172
Revises: 81c63249b710
Create Date: 2025-10-25 01:04:32.264790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ae7c328172'
down_revision = '81c63249b710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_no', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'members', ['member_no'], ['member_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_no')

    # ### end Alembic commands ###
