"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: c58b77e5369a
Revises: 8222b9d514be
Create Date: 2025-10-17 12:48:40.493413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58b77e5369a'
down_revision = '8222b9d514be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_guarantors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_no', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'members', ['member_no'], ['member_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_guarantors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_no')

    # ### end Alembic commands ###
