"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: d4cd95c8699d
Revises: c58b77e5369a
Create Date: 2025-10-17 12:56:18.298775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cd95c8699d'
down_revision = 'c58b77e5369a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('loan_period', sa.Integer(), nullable=True))
        batch_op.drop_column('period')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('loan_period')
        batch_op.drop_column('loan_amount')

    # ### end Alembic commands ###
