"""Add loan, loan_guarantor, loan_schedule, interest models

Revision ID: e47c7a976aab
Revises: d4cd95c8699d
Create Date: 2025-10-17 20:10:52.483857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47c7a976aab'
down_revision = 'd4cd95c8699d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
