"""add saccoAccounts details columns

Revision ID: e6525f2b20bb
Revises: c9f383d83ec9
Create Date: 2025-10-11 12:34:38.508699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6525f2b20bb'
down_revision = 'c9f383d83ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sacco_accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('member_no', sa.String(length=10), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['member_no'], ['members.member_no'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sacco_accounts')
    # ### end Alembic commands ###
