"""members

Revision ID: ecbd72186cd3
Revises: b2e72f0a36db
Create Date: 2025-10-18 13:10:26.026342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbd72186cd3'
down_revision = 'b2e72f0a36db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_interest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_account', sa.String(length=20), nullable=False))

    with op.batch_alter_table('sacco_accounts', schema=None) as batch_op:
        batch_op.drop_column('interest_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))

    with op.batch_alter_table('loan_interest', schema=None) as batch_op:
        batch_op.drop_column('interest_account')

    # ### end Alembic commands ###
