"""Add interest_balance to Loan

Revision ID: f7d968c0b88c
Revises: 24755ae9ce8e
Create Date: 2025-10-20 21:33:04.409116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d968c0b88c'
down_revision = '24755ae9ce8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_balance', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('interest_balance')

    # ### end Alembic commands ###
